# Generated by Django 4.2.24 on 2025-09-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='passwrod',
            new_name='password',
        ),
    ]
