# Generated by Django 4.2.24 on 2025-09-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_rename_passwrod_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='guest', max_length=300),
        ),
    ]
