# Generated by Django 5.2.6 on 2025-09-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
