# Generated by Django 5.2.6 on 2025-09-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Signup',
        ),
    ]
